package vidal.bookshelf.models;
// Generated Feb 27, 2025, 10:22:13 PM by Hibernate Tools 6.6.8.Final


import jakarta.persistence.*;

import java.sql.Date;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name="book"
        ,schema="public"
        ,catalog="postgres"
)
public class Book  implements java.io.Serializable {


    private long id;
    private String name;
    private String author;
    private Date published;
    private long pages;

    public Book() {
    }

    public Book(long id, String name, String author, Date published, long pages) {
        this.id = id;
        this.name = name;
        this.author = author;
        this.published = published;
        this.pages = pages;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "book")
    @SequenceGenerator(name = "book", sequenceName = "book_seq", allocationSize = 1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }


    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name="author", nullable=false, length=255)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="published", nullable=false, length=13)
    public Date getPublished() {
        return this.published;
    }

    public void setPublished(Date published) {
        this.published = published;
    }


    @Column(name="pages", nullable=false)
    public long getPages() {
        return this.pages;
    }

    public void setPages(long pages) {
        this.pages = pages;
    }




}


