package vidal.bookshelf.models;
// Generated Feb 27, 2025, 10:22:13 PM by Hibernate Tools 6.6.8.Final


import jakarta.persistence.*;

/**
 * ReadLog generated by hbm2java
 */
@Entity
@Table(name="read_log"
        ,schema="public"
        ,catalog="postgres"
)
public class ReadLog  implements java.io.Serializable {


    private long id;
    private long book;
    private long year;
    private long month;
    private long day;

    public ReadLog() {
    }


    public ReadLog(long id, long year) {
        this.id = id;
        this.year = year;
    }
    public ReadLog(long id, long book, long year, long month, long day) {
        this.id = id;
        this.book = book;
        this.year = year;
        this.month = month;
        this.day = day;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "read_log")
    @SequenceGenerator(name = "read_log", sequenceName = "read_log_seq", allocationSize = 1)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }


    @Column(name="book")
    public long getBook() {
        return this.book;
    }

    public void setBook(long book) {
        this.book = book;
    }


    @Column(name="year", nullable=false)
    public long getYear() {
        return this.year;
    }

    public void setYear(long year) {
        this.year = year;
    }


    @Column(name="month")
    public long getMonth() {
        return this.month;
    }

    public void setMonth(long month) {
        this.month = month;
    }


    @Column(name="day")
    public long getDay() {
        return this.day;
    }

    public void setDay(long day) {
        this.day = day;
    }




}


